export const FETCH_QUESTIONNAIRES_REQUEST = 'FETCH_QUESTIONNAIRES_REQUEST';
export const FETCH_QUESTIONNAIRES_SUCCESS = 'FETCH_QUESTIONNAIRES_SUCCESS';
export const FETCH_QUESTIONNAIRES_FAILURE = 'FETCH_QUESTIONNAIRES_FAILURE';
export const FETCH_QUESTIONNAIRE_REQUEST = 'FETCH_QUESTIONNAIRE_REQUEST';
export const FETCH_QUESTIONNAIRE_SUCCESS = 'FETCH_QUESTIONNAIRE_SUCCESS';
export const FETCH_QUESTIONNAIRE_FAILURE = 'FETCH_QUESTIONNAIRE_FAILURE';
export const SET_QUESTIONNAIRE = 'SET_QUESTIONNAIRE';
export const FETCH_RESPONSES_REQUEST = 'FETCH_RESPONSES_REQUEST';
export const FETCH_RESPONSES_SUCCESS = 'FETCH_RESPONSES_SUCCESS';
export const FETCH_RESPONSES_FAILURE = 'FETCH_RESPONSES_FAILURE';
export const CREATE_RESPONSE_REQUEST = 'CREATE_RESPONSE_REQUEST';
export const CREATE_RESPONSE_SUCCESS = 'CREATE_RESPONSE_SUCCESS';
export const CREATE_RESPONSE_FAILURE = 'CREATE_RESPONSE_FAILURE';
export const FETCH_VERSION_REQUEST = 'FETCH_VERSION_REQUEST';
export const FETCH_VERSION_SUCCESS = 'FETCH_VERSION_SUCCESS';
export const FETCH_VERSION_FAILURE = 'FETCH_VERSION_FAILURE';
export const UPDATE_RESPONSE_REQUEST = 'UPDATE_RESPONSE_REQUEST';
export const UPDATE_RESPONSE_SUCCESS = 'UPDATE_RESPONSE_SUCCESS';
export const UPDATE_RESPONSE_FAILURE = 'UPDATE_RESPONSE_FAILURE';

export const RESUME_QUESTIONNAIRE = 'RESUME_QUESTIONNAIRE';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION';

export const SET_QUESTION_ANSWER = 'SET_QUESTION_ANSWER';
