export const FETCH_QUESTIONNAIRES_REQUEST = 'FETCH_QUESTIONNAIRES_REQUEST';
export const FETCH_QUESTIONNAIRES_SUCCESS = 'FETCH_QUESTIONNAIRES_SUCCESS';
export const FETCH_QUESTIONNAIRES_FAILURE = 'FETCH_QUESTIONNAIRES_FAILURE';
export const FETCH_QUESTIONNAIRE_REQUEST = 'FETCH_QUESTIONNAIRE_REQUEST';
export const FETCH_QUESTIONNAIRE_SUCCESS = 'FETCH_QUESTIONNAIRE_SUCCESS';
export const FETCH_QUESTIONNAIRE_FAILURE = 'FETCH_QUESTIONNAIRE_FAILURE';
export const SET_QUESTIONNAIRE = 'SET_QUESTIONNAIRE';
export const FETCH_RESPONSE_SUCCESS = 'FETCH_RESPONSE_SUCCESS';
export const FETCH_RESPONSES_REQUEST = 'FETCH_RESPONSES_REQUEST';
export const FETCH_RESPONSES_SUCCESS = 'FETCH_RESPONSES_SUCCESS';
export const FETCH_RESPONSES_FAILURE = 'FETCH_RESPONSES_FAILURE';
export const CREATE_RESPONSE_REQUEST = 'CREATE_RESPONSE_REQUEST';
export const CREATE_RESPONSE_SUCCESS = 'CREATE_RESPONSE_SUCCESS';
export const CREATE_RESPONSE_FAILURE = 'CREATE_RESPONSE_FAILURE';
export const FETCH_VERSION_REQUEST = 'FETCH_VERSION_REQUEST';
export const FETCH_VERSION_SUCCESS = 'FETCH_VERSION_SUCCESS';
export const FETCH_VERSION_FAILURE = 'FETCH_VERSION_FAILURE';
export const UPDATE_RESPONSE_REQUEST = 'UPDATE_RESPONSE_REQUEST';
export const UPDATE_RESPONSE_SUCCESS = 'UPDATE_RESPONSE_SUCCESS';
export const UPDATE_RESPONSE_FAILURE = 'UPDATE_RESPONSE_FAILURE';

export const RESUME_QUESTIONNAIRE = 'RESUME_QUESTIONNAIRE';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION';

export const SET_QUESTION_ANSWER = 'SET_QUESTION_ANSWER';
export const SET_MATRIX_QUESTION_ANSWER = 'SET_MATRIX_QUESTION_ANSWER';
export const SET_RESPONSE = 'SET_RESPONSE';
export const SUBMIT_RESPONSE = 'SUBMIT_RESPONSE';

export const REPEAT_SECTION = 'REPEAT_SECTION';
export const SHOW_SUBMISSION_CONFIRMATION = 'SHOW_SUBMISSION_CONFIRMATION';
export const HIDE_SUBMISSION_CONFIRMATION = 'HIDE_SUBMISSION_CONFIRMATION';

export const MARK_AS_PREFER_NOT_TO_ANSWER = 'MARK_AS_PREFER_NOT_TO_ANSWER';
export const SET_FOLLOW_UP_RESPONSE = 'SET_FOLLOW_UP_RESPONSE';

export const INIT_LARGE_TEXT = 'INIT_LARGE_TEXT';
export const SET_LARGE_TEXT = 'SET_LARGE_TEXT';
