export const FETCH_RELEASES_SUCCESS = 'FETCH_RELEASES_SUCCESS';
export const FETCH_RELEASES_REQUEST = 'FETCH_RELEASES_REQUEST';
export const FETCH_RELEASES_FAILURE = 'FETCH_RELEASES_FAILURE';

export const FETCH_LANDING_PAGE_REQUEST = 'FETCH_LANDING_PAGE_REQUEST';
export const FETCH_LANDING_PAGE_SUCCESS = 'FETCH_LANDING_PAGE_SUCCESS';
export const FETCH_LANDING_PAGE_FAILURE = 'FETCH_LANDING_PAGE_FAILURE';
