export const FETCH_CONSENT_REQUEST = 'FETCH_CONSENTS_REQUEST';
export const FETCH_MAPPED_CONSENTS_SUCCESS = 'FETCH_MAPPED_CONSENTS_SUCCESS';
export const FETCH_CONSENT_TYPES_SUCCESS = 'FETCH_CONSENT_TYPES_SUCCESS';
export const FETCH_CONSENT_SUCCESS = 'FETCH_CONSENTS_SUCCESS';
export const FETCH_CONSENT_FAILURE = 'FETCH_CONSENTS_FAILURE';

export const GET_QUESTIONNAIRE_INFO_SUCCESS = 'GET_QUESTIONNAIRE_INFO_SUCCESS';

export const FETCH_CONSENT_TYPE_MAPPINGS_REQUEST =
  'FETCH_CONSENT_TYPE_MAPPINGS_REQUEST';
export const FETCH_CONSENT_TYPE_MAPPINGS_SUCCESS =
  'FETCH_CONSENT_TYPE_MAPPINGS_SUCCESS';
export const FETCH_CONSENT_TYPE_MAPPINGS_FAILURE =
  'FETCH_CONSENT_TYPE_MAPPINGS_FAILURE';

export const REMOVE_QUESTIONNAIRE_FROM_CONSENT_TYPE_MAPPING =
  'REMOVE_QUESTIONNAIRE_FROM_CONSENT_TYPE_MAPPING';
export const ADD_QUESTIONNAIRE_TO_CONSENT_TYPE_MAPPING =
  'ADD_QUESTIONNAIRE_TO_CONSENT_TYPE_MAPPING';
