export const FETCH_PRICEPLANS_REQUEST = 'FETCH_PRICEPLANS_REQUEST';
export const FETCH_PRICEPLANS_FAILURE = 'FETCH_PRICEPLANS_FAILURE';
export const FETCH_PRICEPLANS_SUCCESS = 'FETCH_PRICEPLANS_SUCCESS';
