export const FETCH_PRICEPLANSMAPPING_REQUEST =
  'FETCH_PRICEPLANSMAPPING_REQUEST';
export const FETCH_PRICEPLANSMAPPING_FAILURE =
  'FETCH_PRICEPLANSMAPPING_FAILURE';
export const FETCH_PRICEPLANSMAPPING_SUCCESS =
  'FETCH_PRICEPLANSMAPPING_SUCCESS';

export const CREATE_PRICEPLANSMAPPING_REQUEST =
  'CREATE_PRICEPLANSMAPPING_REQUEST';
export const CREATE_PRICEPLANSMAPPING_FAILURE =
  'CREATE_PRICEPLANSMAPPING_FAILURE';
export const CREATE_PRICEPLANSMAPPING_SUCCESS =
  'CREATE_PRICEPLANSMAPPING_SUCCESS';

export const UPDATE_PRICEPLANSMAPPING_REQUEST =
  'UPDATE_PRICEPLANSMAPPING_REQUEST';
export const UPDATE_PRICEPLANSMAPPING_FAILURE =
  'UPDATE_PRICEPLANSMAPPING_FAILURE';
export const UPDATE_PRICEPLANSMAPPING_SUCCESS =
  'UPDATE_PRICEPLANSMAPPING_SUCCESS';

export const DELETE_PRICEPLANSMAPPING_REQUEST =
  'DELETE_PRICEPLANSMAPPING_REQUEST';
export const DELETE_PRICEPLANSMAPPING_FAILURE =
  'DELETE_PRICEPLANSMAPPING_FAILURE';
export const DELETE_PRICEPLANSMAPPING_SUCCESS =
  'DELETE_PRICEPLANSMAPPING_SUCCESS';

export const INIT_FORM_DATA = 'INIT_FORM_DATA';
export const CLEAR_FORM_DATA = 'CLEAR_FORM_DATA';
export const SET_FORM = 'SET_FORM';
export const SET_CREATE_EDIT_PANEL = 'SET_CREATE_EDIT_PANEL';
export const SET_DELETE_PANEL = 'SET_DELETE_PANEL';
